version: "3.8"

services:
  agent1:
    image: ros_agent:humble
    container_name: agent1
    command: ros2 run pp agent_node --ros-args -p agent_id:1
    networks: [rosnet]
  agent2:
    image: ros_agent:humble
    container_name: agent2
    command: ros2 run pp agent_node --ros-args -p agent_id:=2
    networks: [rosnet]
  agent3:
    image: ros_agent:humble
    container_name: agent3
    command: ros2 run pp agent_node --ros-args -p agent_id:=3
    networks: [rosnet]
  agent4:
    image: ros_agent:humble
    container_name: agent4
    command: ros2 run pp agent_node --ros-args -p agent_id:=4
    networks: [rosnet]
  agent5:
    image: ros_agent:humble
    container_name: agent5
    command: ros2 run pp agent_node --ros-args -p agent_id:=5
    networks: [rosnet]

networks:
  rosnet:
    driver: bridge