version: '3.8'

services:
  dirac_agent:
    container_name: dirac_agent_${AGENT_ID:-1}
    build:
      context: ..
      dockerfile: dirac_deployment/Dockerfile
    image: dirac-ros2:latest
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - AGENT_ID=${AGENT_ID:-1}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      source /ros2_ws/install/setup.bash &&
      ros2 launch dirac_bringup dirac_agent_bringup.launch.py agent_id:=\$$AGENT_ID"
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge
